### ISSUE TITLE
'SVUI_!Core' tried to call the protected function 'CollectionsJournal:ClearAllPoints()'.

### ISSUE THREAD

**Issue by drveoj** [joev/SVUI-Temp#14]
@klepp0906 says: 1x [ADDON_ACTION_BLOCKED] AddOn 'SVUI_!Core' tried to call the protected function 'CollectionsJournal:ClearAllPoints()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
C: in function `ClearAllPoints'
SVUI_!Core\system\layout.lua:1012: in function 
SVUI_!Core\system\layout.lua:1105: in function 
C: in function UIParent_ManageFramePositions' ...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:21: in function <...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:20> [C]: in functionHide'
...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:274: in function <...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:273>
Locals:

**Comment by drveoj** [comment]
Hi @klepp0906

I can't reproduce this at present. Could you obtain a Taint log for me.

The process for this is as follows: 

In game: type /console taintlog 1 in Chat
Reload UL (/rl in chat) 
Play till you get this error.

Then: 

Find your World of Warcraft directory and look for World of Warcraft\​Logs\​taint.log and then attach it to this bug so I can inspect it 

Note: You'll want to do /console taintlog 0 again in game to turn off taint logging :)

**Comment by klepp0906** [comment]
i just checked the taintlog after re getting the error and its empty? do i need to log out for the data to be written to it or something?

**Comment by klepp0906** [comment]
2x [ADDON_ACTION_BLOCKED] AddOn 'SVUI_!Core' tried to call the protected function 'CollectionsJournal:ClearAllPoints()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C](?): in function `ClearAllPoints'
SVUI_!Core\system\layout.lua:1012: in function <SVUI_!Core\system\layout.lua:1004>
SVUI_!Core\system\layout.lua:1105: in function <SVUI_!Core\system\layout.lua:1101>

[C](?): in function `UIParent_ManageFramePositions'
FrameXML\VehicleSeatIndicator.lua:62: in function`VehicleSeatIndicator_UnloadTextures'
FrameXML\VehicleSeatIndicator.lua:11: in function `VehicleSeatIndicator_SetUpVehicle'
FrameXML\VehicleSeatIndicator.lua:96: in function <FrameXML\VehicleSeatIndicator.lua:93>

Locals:

**Comment by klepp0906** [comment]
1x [ADDON_ACTION_BLOCKED] AddOn 'SVUI_QuestTracker' tried to call the protected function 'CompactRaidFrame6:Hide()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Hide'
FrameXML\CompactUnitFrame.lua:332: in function`CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:280: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:180: in function <FrameXML\CompactUnitFrame.lua:180>

Locals:

**Comment by klepp0906** [comment]
1x [ADDON_ACTION_BLOCKED] AddOn 'SVUI_QuestTracker' tried to call the protected function 'CompactRaidFrame6:Show()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `Show'
FrameXML\CompactUnitFrame.lua:330: in function`CompactUnitFrame_UpdateVisible'
FrameXML\CompactUnitFrame.lua:280: in function `CompactUnitFrame_UpdateAll'
FrameXML\CompactUnitFrame.lua:180: in function <FrameXML\CompactUnitFrame.lua:180>

Locals:

**Comment by klepp0906** [comment]
forgot to clear bugsack.  i suck.  some of those "could" be old. since i dont think theyre date and timestamped, u can interpet better than I.  cleared now so we'll see!  apologies!

**Comment by drveoj** [comment]
I've been running taintlogging for a week on my rig. SVUI isn't tainting anything. If this is still happening then it's another addon causing it - try eliminating them 1 by 1 and see :)
