### ISSUE TITLE
experience bar/rep bar wont appear on infodocks

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#18]
3x ...aceSVUI_!Core\system_reports\reputation-Reputation.lua:57: attempt to compare string with nil
...aceSVUI_!Core\system_reports\reputation-Reputation.lua:57: in function <...aceSVUI_!Core\system_reports\reputation.lua:57>

...aceSVUI_!Core\system_reports\reputation-Reputation.lua:85: in function <...aceSVUI_!Core\system_reports\reputation.lua:59>
...aceSVUI_!Core\system_reports\reputation-Reputation.lua:158: in function `OnInit'
SVUI_!Core\system\reports.lua:363: in function`EnableReport'
SVUI_!Core\system\reports.lua:576: in function `UpdateAllReports'
SVUI_!Options\SVUI_!Options-1.3.2.lua:1843: in function <SVUI_!Options\SVUI_!Options.lua:1843>
(tail call): ?

[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
...
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...dOns\AngryAssignments\libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...ibs\AceVillain-1.0-1\widgets\AceGUIWidget-DropDown.lua:433: in function <...ibs\AceVillain-1.0\widgets\AceGUIWidget-DropDown.lua:424>
(tail call): ?

[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...dOns\AngryAssignments\libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...s\AceGUI-3.0-34\widgets\AceGUIWidget-DropDown-Items.lua:353: in function <...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:343>

Locals:
nil

**Comment by drveoj** [comment]
Thought I'd fixed this but apparently not. Have taken a different approach and should work now.
