### ISSUE TITLE
list of issues :P

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#2]
a few minor things (you may have addressed alreayd, wont know till i install this in about 10 seconds)
- tokens. nothing from legion is on the token tracker for the data dock.
- as windwalker monk even with the resolve meter toggled off in settings, a black/empty resolve meter bar pops up next to my unitframe. (ww never even HAD resolve!) not sure if this happens with other specs/classes.
- brewmaster monks, no stagger meter whatsoever.
- lots of windows arent moveable at the moment. (most notably dungeon finder & interface options window)
- skins for bigwigs are/is broken.  sometimes dont apply, when they do randomly it resizes the bigwigs bars to default from where i had/have them sized.  Big nightmare.  went to bigwigs devs first until i realized it was svui sknning doing it.  disable svui skinning, problem solved.  unfortunately im one for uniformity :Pp for now ive been skinning it manually w/ svui fonts/bars in the bigwigs interface but im just guessing at what kind of bars svui uses for it by default etc.
- creating a 3rd chat window (i make one for loot explicitly) not only does the label not show up on it, but no matter what i have checked inside it filterwise, nothing works.
- loot frames set to grow down, yet they grow up 
- gear changer doesnt work & no slot for newly added 3rd spec
- buff/debuff conditionals arent working properly. for example i have "only me" and "only removeable by me" checked yet they all show anyways. Also my target debuffs (have set to bars fwiw) seem to randomly move down from where I have them set and end up growing over my hotbars instead of ending above them. Also have them set to show up to 6 and the lmit doesnt work either.

-show player experience/reputation on powerbar mouseover not working/mousing over powerbar does nada
- in the name of being thorough, also some of the font size changes arent working.

THANK YOU SO SO MUCH for helping out with this.  The relief and gratitude isnt able to be properly expressed.

**Comment by klepp0906** [comment]
1x [ADDON_ACTION_BLOCKED] AddOn 'SVUI_!Core' tried to call the protected function 'CollectionsJournal:ClearAllPoints()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C](?): in function `ClearAllPoints'
SVUI_!Core\system\layout.lua:1012: in function <SVUI_!Core\system\layout.lua:1004>
SVUI_!Core\system\layout.lua:1105: in function <SVUI_!Core\system\layout.lua:1101>

[C](?): in function `UIParent_ManageFramePositions'
...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:21: in function <...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:20>
[C]: in function`Hide'
...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:274: in function <...ns\Blizzard_TalkingHeadUI\Blizzard_TalkingHeadUI.lua:273>

Locals:

**Comment by klepp0906** [comment]
1x Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua:518: attempt to index field 'selectedButton' (a nil value)
Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua:518: in function `HonorFrame_UpdateQueueButtons'
Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua:600: in function`HonorFrameSpecificList_Update'
Blizzard_PVPUI\Blizzard_PVPUI-1.0.lua:419: in function <Blizzard_PVPUI\Blizzard_PVPUI.lua:416>

Locals:
HonorFrame = HonorFrame {
 0 = <userdata>
 type = "bonus"
 BonusFrame = <unnamed> {
 }
 QueueButton = HonorFrameQueueButton {
 }
 SpecificFrame = HonorFrameSpecificFrame {
 }
 XPBar = <unnamed> {
 }
 Inset = <unnamed> {
 }
 RoleInset = <unnamed> {
 }
}
canQueue = nil
denied = nil
(_temporary) = nil
(_temporary) = HonorFrameQueueButton {
 0 = <userdata>
 Text = HonorFrameQueueButtonText {
 }
 RightSeparator = HonorFrameQueueButton_RightSeparator {
 }
 LeftSeparator = HonorFrameQueueButton_LeftSeparator {
 }
 Right = <unnamed> {
 }
 Middle = <unnamed> {
 }
 Left = <unnamed> {
 }
}
(_temporary) = <function> defined =[C]:-1
(_temporary) = <function> defined _:OnDisable:1
(_temporary) = "attempt to index field 'selectedButton' (a nil value)"

**Comment by drveoj** [comment]
Hi Klepp. Thanks for those. I'm going to split them into individual issues so I can deal with them one at a time. If you find anything else could you submit individual tickets please. Makes it easier for me to manage the list :)

**Comment by drveoj** [comment]
Split into individual issues now. Nice todo list. I might need some more information for some of them :)
