### ISSUE TITLE
experience bar/experience now working, rep bar/rep still not

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#20]
7x ...aceSVUI_!Core\system_reports\reputation-Reputation.lua:57: attempt to compare string with nil
...aceSVUI_!Core\system_reports\reputation-Reputation.lua:57: in function <...aceSVUI_!Core\system_reports\reputation.lua:57>

...aceSVUI_!Core\system_reports\reputation-Reputation.lua:85: in function <...aceSVUI_!Core\system_reports\reputation.lua:59>
...aceSVUI_!Core\system_reports\reputation-Reputation.lua:158: in function `OnInit'
SVUI_!Core\system\reports.lua:363: in function`EnableReport'
SVUI_!Core\system\reports.lua:576: in function `UpdateAllReports'
SVUI_!Options\SVUI_!Options-1.3.2.lua:1843: in function <SVUI_!Options\SVUI_!Options.lua:1843>
(tail call): ?

[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
...
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...dOns\AngryAssignments\libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...ibs\AceVillain-1.0-1\widgets\AceGUIWidget-DropDown.lua:433: in function <...ibs\AceVillain-1.0\widgets\AceGUIWidget-DropDown.lua:424>
(tail call): ?

[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...dOns\AngryAssignments\libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...s\AceGUI-3.0-34\widgets\AceGUIWidget-DropDown-Items.lua:353: in function <...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:343>

Locals:
nil

**Comment by klepp0906** [comment]
how i wish i learned to program.  hardware & networking :(  neither tend to enrich my wow experience very much - never mind making me feel like less of a leech :(

**Comment by drveoj** [comment]
Hi @klepp0906 - I'm very confused. 

Can I suggest (given the number of errors you're seeing - many of which I don't see and can't see how this one can happen now from the code) that you do a complete wipe of your SVUI directories (let's start there and not remove your savedvariables yet although we may have to eventually) and redownload latest updates I've put up today . 

Basically I'd back up your addons directory and remove all the SVUI folders from it, then reinstall clean from the repository on here. 

Let me know how it goes. 

Regards

joev.

**Comment by klepp0906** [comment]
to be fair, i HAVE been overwriting.  so if i remove them all and reinstall from here i wont lose any of my settings yes? 

i mean ive spent DAYS literally, hours and hours on end getting it just right..  hope to never have to do that again lol

**Comment by drveoj** [comment]
No, Your settings will stay (unless you use some 3rd party mod client like Curse in which case don't accept the setting which asks: "Also delete settings" :) 

Best to back up your WTF directory too just in case... don't want to lose those hours! :)

**Comment by klepp0906** [comment]
oh it was SO many hours.  im super anal/perfectionist.  plus i raid in a top 100 guild so things need to be just right for the long haul.  not a lot of time to tinker around.

anyhow, i did delete all the svui addons folders and installed fresh folders from here.

so far so good.

so i dont make yet ANOTHER thread.. im just gonna post this here.

using the git desktop app to get updates i noticed you pushed a fix for the resolve bar.  Upon logging in with a fresh install i still have a resolve bar :P lol

it is only upon logging in until i change specs or something. then if i zone it often comes back.  i tried checking the resolve meter box which brought the empty/black resolve meter template next to my unitframe.  I unchecked it and reloaded again and it was still there.  so hwoever you removed it, its not gone completely.  as usual changing specs makes/made it disappear again.

**Comment by klepp0906** [comment]
and experience still working, rep threw my first error.

3x ...aceSVUI_!Core\system_reports\reputation-Reputation.lua:57: attempt to compare string with nil
...aceSVUI_!Core\system_reports\reputation-Reputation.lua:57: in function <...aceSVUI_!Core\system_reports\reputation.lua:57>

...aceSVUI_!Core\system_reports\reputation-Reputation.lua:85: in function <...aceSVUI_!Core\system_reports\reputation.lua:59>
...aceSVUI_!Core\system_reports\reputation-Reputation.lua:158: in function `OnInit'
SVUI_!Core\system\reports.lua:363: in function`EnableReport'
SVUI_!Core\system\reports.lua:576: in function `UpdateAllReports'
SVUI_!Options\SVUI_!Options-1.3.2.lua:1843: in function <SVUI_!Options\SVUI_!Options.lua:1843>
(tail call): ?

[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
...
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...dOns\AngryAssignments\libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...ibs\AceVillain-1.0-1\widgets\AceGUIWidget-DropDown.lua:433: in function <...ibs\AceVillain-1.0\widgets\AceGUIWidget-DropDown.lua:424>
(tail call): ?

[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...dOns\AngryAssignments\libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...s\AceGUI-3.0-34\widgets\AceGUIWidget-DropDown-Items.lua:353: in function <...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:343>

Locals:
nil

**Comment by klepp0906** [comment]
i do have change rep depending on last rep gain checked if that is meaningful.

fwiw also worked a few versions back.  (before your releases was the last time i tried it, before legion matter of fact - during pre patch i think)

sorry for all the trouble but ty vm for trying to help me and everyone else :Pp

**Comment by klepp0906** [comment]
also, do you truly think the savedvariables could have anything to do with it?

does a way exist to remove the svui settings without touching anything else? 

if you do think it could be an issue, and you can remove it without touching anything else, can i use the generate import string/profile tool to save my settings before doing so?

figured id ask in case we need to go that route, hopefully not!

**Comment by klepp0906** [comment]
so cleared all out svui in all my characters and  account wide and did an uninstall and reinstall again and deleted errors and cache folder in wow.

end result - no rep bar, same error, and the resolve meter still showing up.   Dont think the issue is on my end persay :(

**Comment by klepp0906** [comment]
its gotta be a monk thing.  if i even enable the rep or rep bar on my dock then log out and log back in, whatever dock i assigned it to is now empty of anything.  If i unselect it in the svui settings - everything re appears.

if i can help in any other way with more info let me know, ill try/do anything >.<

**Comment by drveoj** [comment]
Have a try of the updated version and let me know how you get on :)

**Comment by klepp0906** [comment]
unfortunately no dice.  the resolve meter still pops up when i log in (but disappears on its own now without me changing specs which is a start i suppose

the rep still shows nothing.  if i leave it on the dock (invis) and reload then the other 3 items which share that dock also disappear until i remove it.

thi sis the error still 

2x ...aceSVUI_!Core\system_reports\reputation-Reputation.lua:59: attempt to compare string with nil
...aceSVUI_!Core\system_reports\reputation-Reputation.lua:59: in function <...aceSVUI_!Core\system_reports\reputation.lua:57>

...aceSVUI_!Core\system_reports\reputation-Reputation.lua:92: in function <...aceSVUI_!Core\system_reports\reputation.lua:65>
...aceSVUI_!Core\system_reports\reputation-Reputation.lua:244: in function `OnInit'
SVUI_!Core\system\reports.lua:363: in function`EnableReport'
SVUI_!Core\system\reports.lua:576: in function `UpdateAllReports'
SVUI_!Options\SVUI_!Options-1.3.2.lua:1843: in function <SVUI_!Options\SVUI_!Options.lua:1843>
(tail call): ?

[string "safecall Dispatcher[2]"]:9: in function <[string "safecall Dispatcher[2]"]:5>
(tail call): ?
...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0-61.lua:799: in function <...nfig-3.0\AceConfigDialog-3.0\AceConfigDialog-3.0.lua:614>
...
[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...dOns\AngryAssignments\libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...ibs\AceVillain-1.0-1\widgets\AceGUIWidget-DropDown.lua:433: in function <...ibs\AceVillain-1.0\widgets\AceGUIWidget-DropDown.lua:424>
(tail call): ?

[string "safecall Dispatcher[3]"]:9: in function <[string "safecall Dispatcher[3]"]:5>
(tail call): ?
...dOns\AngryAssignments\libs\AceGUI-3.0\AceGUI-3.0-34.lua:314: in function `Fire'
...s\AceGUI-3.0-34\widgets\AceGUIWidget-DropDown-Items.lua:353: in function <...s\AceGUI-3.0\widgets\AceGUIWidget-DropDown-Items.lua:343>

Locals:
nil

fwiw i also tried disabling ALL other addons but svui.  problems listed still exist.

thank you for making an effort - i cant even imagine how complicated it is hunting down these sorts of things :(

**Comment by beerizzzle** [comment]
This same issue exactly is happening on my warrior only. The only difference as far as reputation changes after this happened is I started fishing from the fishing guy in dalaran to gain rep with him. After that it bugged out. I'm fairly certain that it has something to do with it.

**Comment by klepp0906** [comment]
ah good call on that beerizzle.  perhaps thats where the issue lies and that could be when it started for me too as it did work at one point.  the conjuror guy on the island you mean?  

was gonna ask if your panda by chance

**Comment by klepp0906** [comment]
LOL the good news?  The rep bar now shows up!

the bad news?  its showing HATED for every single rep rofl.  HATED in green font nonetheless (im revered w/ them all fwiw)

**Comment by klepp0906** [comment]
the BAR shows correctly, the "reputation" setting (non bar one) does not. (shows the proper percentile just not the proper ranking text)

also to be clear, the tooltip when mousing over it does show properly.  purely the display on the datadock showing improperly.  proper color, im proper text.  hated when should be revered for xample.   happens with all reps not just legion reps fwiw.

**Comment by drveoj** [comment]
One step forward then :)

**Comment by beerizzzle** [comment]
I am not panda but I am hated with the fishing guy

**Comment by drveoj** [comment]
@beerizzzle @klepp0906 Please test latest changes. I've basically rewritten the rep bar and am 99% certain that I've nailed it now. (fingers crossed)
