### ISSUE TITLE
error on demon hunter (may be due to starting zone?)

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#21]
13x ...rfaceSVUI_QuestTracker\SVUI_QuestTracker-1.3.2.lua:372: Usage: SVUI_QuestTrackerScrollFrameScrollBar:SetMinMaxValues(min, max)
[C](?): in function `SetMinMaxValues'
...rfaceSVUI_QuestTracker\SVUI_QuestTracker-1.3.2.lua:372: in function`UpdateDimensions'
...rfaceSVUI_QuestTracker\components\active.lua:314: in function `UpdateActiveObjective'
...rfaceSVUI_QuestTracker\components\quests.lua:489: in function <...rfaceSVUI_QuestTracker\components\quests.lua:457>
...rfaceSVUI_QuestTracker\components\quests.lua:1036: in function`Reset'
...rfaceSVUI_QuestTracker\components\quests.lua:1050: in function <...rfaceSVUI_QuestTracker\components\quests.lua:1048>

[C](?): in function `Hide'
FrameXML\UIParent.lua:2320: in function`SetUIPanel'
FrameXML\UIParent.lua:2347: in function `MoveUIPanel'
FrameXML\UIParent.lua:2378: in function`HideUIPanel'
FrameXML\UIParent.lua:2052: in function <FrameXML\UIParent.lua:2044>
[C](?): in function `SetAttribute'
FrameXML\UIParent.lua:2846: in function`HideUIPanel'
FrameXML\UIParent.lua:2812: in function `ToggleFrame'
FrameXML\WorldMapFrame.lua:219: in function`ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:
(_temporary) = SVUI_QuestTrackerScrollFrameScrollBar {
 0 = <userdata>
 Panel = <unnamed> {
 }
 noStyleUpdate = true
 SetFrameLevel = <function> defined =[C](?):-1
}
(_temporary) = 1
(*temporary) = -6.0000299215317

**Comment by klepp0906** [comment]
also worth nothing

A) demon hunter doesnt have the crazy resolve bar popping up on login

B) demon hunter has no issues with reputation bar working.

how are these affecting one toon/class and not the other.  I use the monk as the master profile (as its my main) and i also used its import key when i first started the demon hunter so everything should be 100% identical between them (except i changed the demon hunter class color from green to purple)

**Comment by klepp0906** [comment]
so i tried resetting to default and using the demon hunter export key on my monk.  now my top dock wont show anythign and the export window after hitting import from key gives me this

Reports [Load]: @(09/19/16 19:59:55) - ...ace\AddOns\SVUI_!Core\system_reports\reputation.lua:57: attempt to compare string with nil

FightOMatic [Load]: @(09/19/16 19:59:58) - ...ace\AddOns\SVUI_!Core\system_reports\reputation.lua:57: attempt to compare string with nil

**Comment by drveoj** [comment]
Have uploaded new changes which should fix this (fingers crossed).

Please verify.

**Comment by drveoj** [comment]
@klepp0906 Can you have a look and see if this still happens? I think I've fixed but don't want to close until you verify that it's not happening any more. 

Many thanks. 

joev

**Comment by klepp0906** [comment]
I've been on him sparingly but I'll be on him quite a bit today.  Haven't seen it recently but if you'd like, wait till tonight for the 100%
