### ISSUE TITLE
Errors on HPS meter

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#26]
hps meter has me doing 3million hps...

dps meter seems roughly mroe accurate has me doing 70 (on mw) when actually doing 50 but being 2.8 million off is scary business lol.

as usual, any more info you need, any screenshots, any taintlogs etc... please speak up.  ill help in any small way i can.

**Comment by drveoj** [comment]
Could you do me a screen m8. Some of these features I don't use at all so I have no idea what they should look like :)

**Comment by klepp0906** [comment]
you betcha, let me clear out my ss folder and ill get some together for stuff ;)

sorry woulda gotten to this yesterday but w/ EN opening it was long hours and up late >.<

**Comment by drveoj** [comment]
@klepp0906 Spot check on this one. Still seeing the same problem? (if so, can you do me an SS?) - Thx - joev

**Comment by klepp0906** [comment]
Did you finaggle with the hps only or the dps meter too?

I only ask cause I'm not playing a healing class atm (guild needed ranged dps ugh).  

I can either check for accuracy with dps dock meter (if related), u can see if someone else can check, or I can begrudgingly re sub my healer account.

Hoping for option #1!

Judging by my email box you got busy today!  Thanks you :)

**Comment by drveoj** [comment]
Please see: https://github.com/failcoder/supervillain-ui/issues/1
