### ISSUE TITLE
Item level displaying incorrectly in bags

### ISSUE THREAD

**Issue by jonnyapps** [joev/SVUI-Temp#30]
Item levels are frequently incorrect in my bags. They can be higher, though are mainly lower, than they should be.

F.ex if I unequip my artifact weapon, which is 860, it shows as 760 in my bags. Can provide a screenshot later if needed.

**Comment by klepp0906** [comment]
this/confirmed.  though it "may" be an issue with blizzards api atm.  I know a lot of items wont show the tooltip when you mouse over them and say "fetching item data" or something of the sort. 

i heard artifacts werent even in the api last i checked.  simcraft devs had to finaggle something up themselves for it.  this was weeks back so who knows.

atm a bit livid over blizzard having the time to brag about sales but not the time to fix disconnects with the withered scenario n such.

**Comment by drveoj** [comment]
no. This is a bug in SVUI for sure.
