### ISSUE TITLE
Demon hunter metamorphosis displays on buffbars but not auras

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#39]
as title says.  demon hunters metamorphosis displays above unitframe but nothing up where buffs go by minimap.

may be the same with other DH abilities - havent played it enough to see, just noticed this.

checked blacklists/config and its not even in there ie: not even listed as an option to check or uncheck anyways.  again, assume this may be the case with a lot of DH stuff considering theyre brand new and mung was gone by that point.

thank you!

**Comment by drveoj** [comment]
See #83  - This is because a combination of filtering and partially updated code for consolidation and hyperauras is unfinished. Instructions to work-around provided in referenced issue.
