### ISSUE TITLE
Ugh! just as i was getting excited!

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#40]
is this a new one?  what is vehicileseat?  this from the popup when you  use the grand expedition  yak?  or perhaps mounting the npc's in the stormheim pvp wq?

no clue but heres the error.  only one im getting.  the similar one w/ movingtalkinghead is now gone since i ditched that addon.

1x [ADDON_ACTION_BLOCKED] AddOn 'SVUI_!Core' tried to call the protected function 'CollectionsJournal:ClearAllPoints()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C](?): in function `ClearAllPoints'
SVUI_!Core\system\layout.lua:1015: in function <SVUI_!Core\system\layout.lua:1007>
SVUI_!Core\system\layout.lua:1108: in function <SVUI_!Core\system\layout.lua:1104>

[C](?): in function `UIParent_ManageFramePositions'
FrameXML\VehicleSeatIndicator.lua:62: in function`VehicleSeatIndicator_UnloadTextures'
FrameXML\VehicleSeatIndicator.lua:106: in function <FrameXML\VehicleSeatIndicator.lua:93>

Locals:

**Comment by klepp0906** [comment]
1x [ADDON_ACTION_BLOCKED] AddOn 'SVUI_!Core' tried to call the protected function 'CollectionsJournal:ClearAllPoints()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C](?): in function `ClearAllPoints'
SVUI_!Core\system\layout.lua:1015: in function <SVUI_!Core\system\layout.lua:1007>
SVUI_!Core\system\layout.lua:1108: in function <SVUI_!Core\system\layout.lua:1104>

[C](?): in function `UIParent_ManageFramePositions'
FrameXML\ExtraActionBar.lua:17: in function`ExtraActionBar_Update'
FrameXML\ActionBarController.lua:87: in function <FrameXML\ActionBarController.lua:53>

Locals:

**Comment by klepp0906** [comment]
none of these flicker a light bulb eh? still trying to pin down exactly when they go off.  gonna turn on bugsack sounds so i hear when i get one, hopefully that helps me find out exactly what triggers it.

thanks for you work.. your given the entire community of users hope <3

**Comment by klepp0906** [comment]
1x SVUI_!Core\system\layout.lua:835: bad argument #1 to 'pairs' (table expected, got nil)

SVUI_!Core\system\layout.lua:835: in function `Toggle'
SVUI_!Core\system\layout.lua:1430: in function`?'
SVUI_!Core\system\slash.lua:78: in function `?'
FrameXML\ChatFrame.lua:4332: in function`ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4000: in function `ChatEdit_SendText'
FrameXML\ChatFrame.lua:4036: in function <FrameXML\ChatFrame.lua:4032>
[C]: in function`ChatEdit_OnEnterPressed'
[string "_:OnEnterPressed"]:1: in function <[string "_:OnEnterPressed"]:1>

Locals:
(_temporary) = nil
(_temporary) = "table expected, got nil"
 = <function> defined =[C](?):-1

**Comment by drveoj** [comment]
Fixed in latest update
