### ISSUE TITLE
new error 

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#46]
1x ...libs\LibReputationData-1.0\LibReputationData-1.0-1.lua:218: attempt to index global 'self' (a nil value)
...libs\LibReputationData-1.0\LibReputationData-1.0-1.lua:218: in function `?'
...libs\LibReputationData-1.0\LibReputationData-1.0-1.lua:31: in function <...libs\LibReputationData-1.0\LibReputationData-1.0.lua:31>

Locals:

**Comment by drveoj** [comment]
I think you may have downloaded a version yesterday before I fixed that bug (sorry I was very busy till 2:30am yesterday fixing little niggles in that lib and with the Rep Bar it supports :)) - I'm sure it's gone in the current code (there's no "self" references to be found anywhere)

Make sure you delete your old SVUI_!Core before copying in the latest one just in case :)

**Comment by klepp0906** [comment]
just got it this morning, adn did delete all of them before re adding from master.

also just got this error.

1x ...ars\libs\LibActionButton-1.0\LibActionButton-1.0-57.lua:1205: attempt to index field 'parent' (a nil value)
...ars\libs\LibActionButton-1.0\LibActionButton-1.0-57.lua:1205: in function <...ars\libs\LibActionButton-1.0\LibActionButton-1.0.lua:1202>

Locals:

and no worries - take your time, we all love you for doing this <3

**Comment by drveoj** [comment]
Could you download again? I think I did some work this afternoon but can't remember if it was on that. In the latest tree it's clear there are no references to 'self' in LibReputation.lua so can't be from there. I did have this bug in an earlier version so maybe that's what I fixed earlier today :)

**Comment by klepp0906** [comment]
You bet! Doing so now :)
