### ISSUE TITLE
Every time upon loggin window moving back/resetting

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#47]
I move the talkinghead window to the top as we've discussed.   Problem is, now every time i quit wow and restart - the next day its back at the bottom again until I move it to the top lol.

**Comment by drveoj** [comment]
SVUI doesn't manage that window at all mate (yet) ;)

**Comment by klepp0906** [comment]
Oh? That's odd cause the add on I downloaded to move it is gone.

Add in the fact that Add on only exists because it's not moveable by blizzard.

I'm sure you would know better than I but you certain your not mistaken?

Any chance we can get it to manage it? Re moving it each time is getting tiring and I could re download the other add on but then it was contributing to lua errors afaik.

Advise :p

**Comment by drveoj** [comment]
Sorry. I tell a lie. I added it into the list of frames for SVUI to manage the position of but I haven't added the code to store it's position. Doh! :) I'll get to that might have to wait until I'm re-skinning it as well (after all it represents a fellow supervillain or one of those darned Hero types talking with you... it should look the part!)

**Comment by drveoj** [comment]
Fixed in latest update

**Comment by drveoj** [comment]
duplicate pf #52
