### ISSUE TITLE
nother error 

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#48]
1x [ADDON_ACTION_BLOCKED] AddOn 'SVUI_!Core' tried to call the protected function 'SVUI_DockBottomRightAlert:SetHeight()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C]: in function `SetHeight'
SVUI_!Core\system\dock.lua:1518: in function`Deactivate'
SVUI_!Core\system\dock.lua:824: in function <SVUI_!Core\system\dock.lua:822>
SVUI_!Core\system\dock.lua:1306: in function <SVUI_!Core\system\dock.lua:1282>

Locals:

**Comment by drveoj** [comment]
Fixed in latest update
