### ISSUE TITLE
talking head window

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#52]
seems to be randomly (more often than not) now opening to the full length of the screen and turning it black.  have to clos eit via the red x to be able to see again or wait until theyre done flapping their gums 📦 

also as i mentioned in the closed area, still not savnig its position it seems.

**Comment by klepp0906** [comment]
only noticed this starting this morning and only in the withered scenario btw. (so far)

EDIT: nope just happened in suramar city >.<

**Comment by drveoj** [comment]
Noticed this myself and I've a fair idea why it's happening. My simple fix seems to have made things worse. I'll back it out and look at a more permanent fix.
