### ISSUE TITLE
new errors, not sure if svui or not?

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#53]
199x ...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:24: Usage: GetAppearanceInfoByID(artifactAppearanceID)
[C]: in function `GetAppearanceInfoByID'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:24: in function`RefreshModel'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:180: in function `TryRefresh'
...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:81: in function <...ddOns\Blizzard_ArtifactUI\Blizzard_ArtifactPerks.lua:80>

Locals:
(*temporary) = nil

---

2x ...ars\libs\LibActionButton-1.0\LibActionButton-1.0-57.lua:1205: attempt to index field 'parent' (a nil value)
...ars\libs\LibActionButton-1.0\LibActionButton-1.0-57.lua:1205: in function <...ars\libs\LibActionButton-1.0\LibActionButton-1.0.lua:1202>

Locals:
self = LAB10ChargeCooldown2 {
 0 = <userdata>
}
(_temporary) = nil
(_temporary) = LAB10ChargeCooldown2 {
 0 = <userdata>
}
(_temporary) = UIParent {
 0 = <userdata>
 firstTimeLoaded = 1
 variablesLoaded = true
}
(_temporary) = "attempt to index field 'parent' (a nil value)"
tinsert = <function> defined =[C]:-1
lib = <table> {
 GetAllButtons = <function> defined @SVUI_ActionBars\libs\LibActionButton-1.0\LibActionButton-1.0.lua:367
 nonActionButtons = <table> {
 }
 ACTION_HIGHLIGHT_MARKS = <table> {
 }
 callbacks = <table> {
 }
 numOverlays = 1
 activeButtons = <table> {
 }
 UnregisterAllCallbacks = <function> defined @AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:200
 unusedOverlayGlows = <table> {
 }
 actionButtons = <table> {
 }
 RegisterCallback = <function> defined @AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:116
 UnregisterCallback = <function> defined @AngryAssignments\libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:179
 NumChargeCooldowns = 4
 buttonRegistry = <table> {
 }
 CreateButton = <function> defined @SVUI_ActionBars\libs\LibActionButton-1.0\LibActionButton-1.0.lua:143
 eventFrame = <unnamed> {
 }
 ChargeCooldowns = <table> {
 }
}

**Comment by drveoj** [comment]
The first one has nothing to do with SVUI as far as I can tell as SVUI doesn't touch the GetAppearanceInfoByID or anything to do with Artifact Perks (yet).

The second errorseems to be an incompatability with AngryAssignments... I'll have a look at it and see what I can do.

**Comment by drveoj** [comment]
No further update or sight of this error. I'm going to assume it's now closed by updating to latest LibActionButton
