### ISSUE TITLE
first time error since last push

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#55]
10x ...Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua:685: attempt to get length of local 'items' (a nil value)
...Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua:685: in function `GarrisonLandingPageReportMission_FilterOutCombatAllyMissions'
...Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua:449: in function`GarrisonLandingPageReportList_UpdateItems'
...Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua:211: in function <...Blizzard_GarrisonUI\Blizzard_GarrisonLandingPage.lua:207>

Locals:
items = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = nil
(_temporary) = "attempt to get length of local 'items' (a nil value)"

**Comment by drveoj** [comment]
Haven't changed anything regarding garrisons since I started on the codebase. 
Can you describe when this happens?

Also: Just given the number of issues you have Klepp, I think you need to give me your Addon List because almost all of these are specific to your setup and I can't reproduce on mine so I need to replicate your setup to be able to figure out where the incompatabilities are happening.

**Comment by drveoj** [comment]
Note: This might be a error in the actual Blizzard UI: 

http://eu.battle.net/forums/en/wow/topic/17613361342

**Comment by klepp0906** [comment]
Will keep an eye if it pops up again.  With all the issues blizzard has had lately with their crz and servers and disconnecting - wouldn't surprise me.

I'll get you an add on list regRdless.  I don't use anything un common, nor a huge amount of them but hopefully it helps.

I always get an "interface action failed due to add on" and a "your Ui is creating too many errors" text in my chat box too fwiw.

Not sure how many it takes to trigger that as when I check bugsack it's usually like 4..

Anyhow! Will post back.  Thank you joe

**Comment by drveoj** [comment]
We haven't seen or heard this one in a while and no-one else is reporting it so gonna call it. 

Time of death: now :)
