### ISSUE TITLE
new error s

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#60]
1x [ADDON_ACTION_BLOCKED] AddOn 'SVUI_!Core' tried to call the protected function '<unnamed>:Hide()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C](?): in function `Hide'
FrameXML\WorldMapActionButton.lua:58: in function`Clear'
FrameXML\WorldMapActionButton.lua:67: in function `Refresh'
FrameXML\WorldMapActionButton.lua:19: in function`SetMapAreaID'
FrameXML\WorldMapFrame.lua:1140: in function `WorldMapFrame_Update'
FrameXML\WorldMapFrame.lua:2869: in function`WorldMapFrame_UpdateMap'
FrameXML\WorldMapFrame.lua:408: in function <FrameXML\WorldMapFrame.lua:394>
[C](?): in function `SetMapToCurrentZone'
FrameXML\WorldMapFrame.lua:341: in function <FrameXML\WorldMapFrame.lua:320>

[C](?): in function `Show'
FrameXML\UIParent.lua:2336: in function`SetUIPanel'
FrameXML\UIParent.lua:2138: in function `ShowUIPanel'
FrameXML\UIParent.lua:2048: in function <FrameXML\UIParent.lua:2044>
[C]: in function`SetAttribute'
FrameXML\UIParent.lua:2830: in function `ShowUIPanel'
FrameXML\UIParent.lua:2814: in function`ToggleFrame'
FrameXML\WorldMapFrame.lua:236: in function `ToggleWorldMap'
[string "TOGGLEWORLDMAP"]:1: in function <[string "TOGGLEWORLDMAP"]:1>

Locals:

1x ...ars\libs\LibActionButton-1.0\LibActionButton-1.0-57.lua:1205: attempt to index field 'parent' (a nil value)
...ars\libs\LibActionButton-1.0\LibActionButton-1.0-57.lua:1205: in function <...ars\libs\LibActionButton-1.0\LibActionButton-1.0.lua:1202>

Locals:

**Comment by drveoj** [comment]
Think this was caused by the fact that we're on an older version of LibActionButton. Have updated and hopefully this will go away as a consequence (the offending code in LAB is better protected now.
