### ISSUE TITLE
error on dh

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#63]
1x [ADDON_ACTION_BLOCKED] AddOn 'SVUI_QuestTracker' tried to call the protected function '<unnamed>:Hide()'.
!BugGrabber\BugGrabber.lua:573: in function <!BugGrabber\BugGrabber.lua:573>
[C](?): in function `Hide'
FrameXML\WorldMapActionButton.lua:58: in function`Clear'
FrameXML\WorldMapActionButton.lua:67: in function `Refresh'
FrameXML\WorldMapActionButton.lua:19: in function`SetMapAreaID'
FrameXML\WorldMapFrame.lua:390: in function <FrameXML\WorldMapFrame.lua:353>

[C](?): in function `Hide'
FrameXML\UIParent.lua:2320: in function`SetUIPanel'
FrameXML\UIParent.lua:2347: in function `MoveUIPanel'
FrameXML\UIParent.lua:2378: in function`HideUIPanel'
FrameXML\UIParent.lua:2052: in function <FrameXML\UIParent.lua:2044>
[C](?): in function `SetAttribute'
FrameXML\UIParent.lua:2846: in function`HideUIPanel'
FrameXML\UIParent.lua:3014: in function `CloseWindows'
FrameXML\UIParent.lua:3053: in function <FrameXML\UIParent.lua:3043>
[C]: in function`securecall'
FrameXML\UIParent.lua:3658: in function `ToggleGameMenu'
[string "TOGGLEGAMEMENU"]:1: in function <[string "TOGGLEGAMEMENU"]:1>

Locals:

**Comment by drveoj** [comment]
I don't know what's going on here. Just giving me the error with no context doesn't help me locate the error. What were the circumstances that this error occurs? What were you doing? What windows were open(ing) or close(ing)?

**Comment by klepp0906** [comment]
Oh I apologize.  I assumed the error pointed you in the right direction.  A lot of times I don't notice them as they happen.  Will have to keep a better watch going forward now that I know.

**Comment by drveoj** [comment]
@klepp0906 Thanks. For this type of error basically it's not SVUI directly but something else calling a function which SVUI has hooked on to or overridden which causes the error. In order to determine which function I need to know when it happens. 

Come join us on discord! Think it's about time we discussed all these issues you've been having in real-time :) 

https://discord.gg/4VJdSsc

joe

**Comment by klepp0906** [comment]
I intend to. TBH we have just been busy with guild matters and coincidentally enough mumble service has been kinda poor and we are talking about moving to discord.

It's on my to do list!

As far as issues go - your chipping away at em, slowly but steadily.  The amount of progress you've made in the amount of time you've made it is amazing.

Hope it's not too taxing on ya :(

**Comment by drveoj** [comment]
Not heard anything about this for a while. Going to assume it's closed
