### ISSUE TITLE
artifact window still wonky

### ISSUE THREAD

**Issue by klepp0906** [joev/SVUI-Temp#64]
changed specs to heal a dungeon and the artifact datadocklet says NO ARTIFACT.  mousing over it still shows the correct info in the tooltip however.

couldnt find where i initially posted about the issue with it and i know u pushed a fix a few hours back that i "assume" was directed towards it.  if not - disregard ofc.

**Comment by drveoj** [comment]
Yep. I messed it up then fixed it :). Please try latest push. :)

## 

Joe Vaughan

**Comment by drveoj** [comment]
Can you check if it's still happening with latest push please @klepp0906 - I've not got access to Wow (or much of anything) at the moment as my internet is currently down (my cable provider says it's a known problem affecting my whole area and will be fixed promptly... next Friday, the 7th of October! What customer service!)

**Comment by drveoj** [comment]
@klepp0906 Just to note: The artefact bar only shows the "Active" artefact. If you switch specs and you're still wearing the old-spec artefact it's not considered to be "Active" - once you swap in the new artefact (for the current spec) then that becomes active and the bar should pick it up (I believe). Can you double check if this is the behaviour you're observing (in which case it's behaving as it should).

**Comment by drveoj** [comment]
Certain this is fixed and working properly now. Verified myself yesterday evening (had to go and get a second artefact on my main which I hadn't bothered with since I only ever tank on her :>)
