### ISSUE TITLE
Hearthstone button not detecting Inn keepers daughter.

### ISSUE THREAD

**Issue by finalsliver** [joev/SVUI-Temp#66]
http://www.wowhead.com/item=64488/the-innkeepers-daughter

Now a toy so not actively in the bag. acts as an alternative hearthstone.  
Is it possible to add detection for this toy and if so use on the hearthstone dock in the bottom left?

other such toys that share cooldown/ability with hearthstone
http://www.wowhead.com/item=93672/dark-portal
http://www.wowhead.com/item=54452/ethereal-portal

---

Edit: Additionally; without a normal hearthstone in your inventory, the button will not even appear, despite having both a Dalaran and Garrison hearthstone in my inventory.

**Comment by drveoj** [comment]
Good report @finalsliver. All those are in Mung's list of travel items but the toybox items don't work the same anymore. Am recoding around it.

**Comment by drveoj** [comment]
Fixed in latest updates
