### ISSUE TITLE
Token docket issue. 

### ISSUE THREAD

**Issue by finalsliver** [joev/SVUI-Temp#67]
When hovering over the token docket, 'Ancient Mana' is given a cap of 300. as this can expand with in game unlocks up to 2000 (at the moment. possibly more later) it leads to my current value of 1745/300.

Here's an image of my hover-over menu ingame.
http://puu.sh/rwI43/396653a218.jpg

**Comment by drveoj** [comment]
The update I pushed this morning fixed this (cos I spotted it myself yesterday too :) . Please re-download and apply.

**Comment by finalsliver** [comment]
:D Thanks on the quick fix
