### ISSUE TITLE
Action Bar

### ISSUE THREAD

**Issue by Murphy107j** [joev/SVUI-Temp#71]
I have updated to the latest fixes you have done but I have noticed now on my bars it doesn't show procs like for my unholy death knight it doesn't show sudden doom or the dark succor. the spell doesn't light up like it did before

**Comment by finalsliver** [comment]
I've noticed this as well on my Arcane mage. 

When I gained a charge of 'Arcane missiles' there would be a glow affect around the appropriate key.

Only difference in the install is the two different versions of SVUI 
Last official update | last nights build.

**Comment by drveoj** [comment]
Ahhh... I like the easy ones to fix :) Please download latest update.
