### ISSUE TITLE
Combo points hidden or inconsistent

### ISSUE THREAD

**Issue by kayleighraven** [joev/SVUI-Temp#74]
Druid combo points are appearing behind the energy bar on blizzard's Personal Resource Display. Sometimes can be made visible by disabling "superstyling" in Nameplates but on/off not consistent. If using Druid classbar instead, combo points don't appear until target is out of range or player is out of combat.
![wowscrnshot_100316_163405](https://cloud.githubusercontent.com/assets/22617938/19077261/c9f9167a-8a43-11e6-8de1-a1e33732e6a0.jpg)

**Comment by drveoj** [comment]
Excellent report - I'll get on it :)
