### ISSUE TITLE
Getting this error with my rogue...

### ISSUE THREAD

**Issue by lkj61** [joev/SVUI-Temp#80]
Frames [Load]: @(10/07/16 20:39:20) - ...ace\AddOns\SVUI_UnitFrames\class_resources\rogue.lua:124: attempt to index field '?' (a nil value)

**Comment by drveoj** [comment]
Ok. Will look into it (will be later this evening as I'm out and about at
present :))

## 

Joe Vaughan

**Comment by lkj61** [comment]
Thanks!  Much appreciate all the work you are doing for us fans of SVUI. 😀
