### ISSUE TITLE
Multiple lua errors for unitframes

### ISSUE THREAD

**Issue by kayleighraven** [joev/SVUI-Temp#84]
I'm now getting loads of lua errors starting from log in and again when I click on NPCs. The target unitframe itself seems to be deactivated until I disable and re-enable it in settings. I've grabbed some of the errors I get. I recognise the "Druidness" thing from somewhere (as in I think I've named something that, but can't find it in anything obvious like auras or outfits etc).

Message: ...tFrames\libs\plugins\oUF_Druidness\oUF_Druidness.lua:165: attempt to index field '?' (a nil value)
Time: 10/09/16 12:27:56
Count: 1
Stack: ...tFrames\libs\plugins\oUF_Druidness\oUF_Druidness.lua:165: in function <...tFrames\libs\plugins\oUF_Druidness\oUF_Druidness.lua:140>
...tFrames\libs\plugins\oUF_Druidness\oUF_Druidness.lua:180: in function `func'
Interface\AddOns\SVUI_UnitFrames\libs\oUF\ouf.lua:184: in function`?'
Interface\AddOns\SVUI_UnitFrames\libs\oUF\events.lua:88: in function <Interface\AddOns\SVUI_UnitFrames\libs\oUF\events.lua:74>

Locals: self = SVUI_Player {
 0 = <userdata>
 PortraitTexture = <unnamed> {
 }
 CombatFade = false
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\castbar.lua:248
 __mousetags = <table> {
 }
 Resting = <unnamed> {
 }
 UNIT_MAXHEALTH = <table> {
 }
 PLAYER_UPDATE_RESTING = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\resting.lua:22
 UNIT_POWER_FREQUENT = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\plugins\oUF_Druidness\oUF_Druidness.lua:90
 UPDATE_SHAPESHIFT_FORM = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\plugins\oUF_Druidness\oUF_Druidness.lua:67
 Aggro = SVUI_PlayerThreatAlert {
 }
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\castbar.lua:188
 ActionPanel = <unnamed> {
 }
 alternativeUnit = "vehicle"
 style = "SVUI_Player"
 ClassBar = "Druidness"
 InfoPanelRight = <unnamed> {
 }
 UNIT_EXITED_VEHICLE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\ouf.lua:51
 UNIT_CONNECTION = <table> {
 }
 Debuffs = SVUI_PlayerDebuffs {
 }
 UNIT_HEAL_PREDICTION = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\healprediction.lua:98
 UpdateBackdrop = <function> defined @Interface\AddOns\SVUI_!Core\system\api.lua:498
 Grip = SVUI_Player_MOVE {
 }
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\castbar.lua:202
 UNIT_SPELLCAST_STOP = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\castbar.lua:222
 UNIT_AURA = <table> {
 }
 Threat = <unnamed> {
 }
 HealPrediction = <table> {
 }
 Experience = PlayerFrameExperienceBar {
 }
 CHARACTER_POINTS_CHANGED = <table> {
 }
 ___key = "player"
 BackdropNeedsUpdate = true
 InfoPanelLeft = <unnamed> {
 }
 Combat = <unnamed> {
 }
 UNIT_MODEL_CHANGED = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\portraits.lua:88
 __tags = <table> {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\ouf.lua:51
 UNIT_PORTRAIT_UPDATE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\portraits.lua:88
 RefreshClassBar = <function> defined @Interface\AddOns\SVUI_UnitFrames\class_resources\druid.lua:97
 colors = <table> {
 }
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\castbar.lua:174
 RAID_TARGET_UPDATE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\ricons.lua:27
 UNIT_POWER = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\power.lua:87
 Update = <function> defined @Interface\AddOns\SVUI_UnitFrames\frames.lua:178
 SetBackdropBorderColor = <function> defined =[C]:-1
 TextGrip = <unnamed> {
 }
 StatusPanel = <unnamed> {
 }
 Panel = <unnamed> {
 }
 UNIT_POWER_BAR_SHOW = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\power.lua:87
 LossOfControl = <unnamed> {
 }
 Castbar = <unnamed> {
 }
 UNIT_DISPLAYPOWER = <table> {
 }
 UPDATE_EXHAUSTION = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\plugins\oUF_Experience\oUF_Experience.lua:82
 SetBackdrop = <function> defined =[C]:-1
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\threat.lua:29
 UNIT_THREAT_LIST_UPDATE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\
Message: ...tFrames\libs\plugins\oUF_Druidness\oUF_Druidness.lua:165: attempt to index field '?' (a nil value)
Time: 10/09/16 12:29:08
Count: 1
Stack: ...tFrames\libs\plugins\oUF_Druidness\oUF_Druidness.lua:165: in function `func'
Interface\AddOns\SVUI_UnitFrames\libs\oUF\events.lua:125: in function`?'
Interface\AddOns\SVUI_UnitFrames\libs\oUF\events.lua:88: in function <Interface\AddOns\SVUI_UnitFrames\libs\oUF\events.lua:74>
[C]: in function `CameraOrSelectOrMoveStop'
[string "CAMERAORSELECTORMOVE"]:4: in function <[string "CAMERAORSELECTORMOVE"]:1>

Locals: self = SVUI_Player {
 0 = <userdata>
 PortraitTexture = <unnamed> {
 }
 CombatFade = false
 UNIT_SPELLCAST_CHANNEL_START = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\castbar.lua:248
 __mousetags = <table> {
 }
 Resting = <unnamed> {
 }
 UNIT_MAXHEALTH = <table> {
 }
 PLAYER_UPDATE_RESTING = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\resting.lua:22
 UNIT_POWER_FREQUENT = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\plugins\oUF_Druidness\oUF_Druidness.lua:90
 UPDATE_SHAPESHIFT_FORM = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\plugins\oUF_Druidness\oUF_Druidness.lua:67
 Aggro = SVUI_PlayerThreatAlert {
 }
 UNIT_SPELLCAST_NOT_INTERRUPTIBLE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\castbar.lua:188
 ActionPanel = <unnamed> {
 }
 alternativeUnit = "vehicle"
 style = "SVUI_Player"
 ClassBar = "Druidness"
 InfoPanelRight = <unnamed> {
 }
 UNIT_EXITED_VEHICLE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\ouf.lua:51
 UNIT_CONNECTION = <table> {
 }
 Debuffs = SVUI_PlayerDebuffs {
 }
 UNIT_HEAL_PREDICTION = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\healprediction.lua:98
 UpdateBackdrop = <function> defined @Interface\AddOns\SVUI_!Core\system\api.lua:498
 Grip = SVUI_Player_MOVE {
 }
 UNIT_SPELLCAST_DELAYED = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\castbar.lua:202
 UNIT_SPELLCAST_STOP = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\castbar.lua:222
 UNIT_AURA = <table> {
 }
 Threat = <unnamed> {
 }
 HealPrediction = <table> {
 }
 Experience = PlayerFrameExperienceBar {
 }
 CHARACTER_POINTS_CHANGED = <table> {
 }
 ___key = "player"
 BackdropNeedsUpdate = true
 InfoPanelLeft = <unnamed> {
 }
 Combat = <unnamed> {
 }
 UNIT_MODEL_CHANGED = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\portraits.lua:88
 __tags = <table> {
 }
 UNIT_ENTERED_VEHICLE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\ouf.lua:51
 UNIT_PORTRAIT_UPDATE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\portraits.lua:88
 RefreshClassBar = <function> defined @Interface\AddOns\SVUI_UnitFrames\class_resources\druid.lua:97
 colors = <table> {
 }
 UNIT_SPELLCAST_INTERRUPTIBLE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\castbar.lua:174
 RAID_TARGET_UPDATE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\ricons.lua:27
 UNIT_POWER = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\power.lua:87
 Update = <function> defined @Interface\AddOns\SVUI_UnitFrames\frames.lua:178
 SetBackdropBorderColor = <function> defined =[C]:-1
 TextGrip = <unnamed> {
 }
 StatusPanel = <unnamed> {
 }
 Panel = <unnamed> {
 }
 UNIT_POWER_BAR_SHOW = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\power.lua:87
 LossOfControl = <unnamed> {
 }
 Castbar = <unnamed> {
 }
 UNIT_DISPLAYPOWER = <table> {
 }
 UPDATE_EXHAUSTION = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\plugins\oUF_Experience\oUF_Experience.lua:82
 SetBackdrop = <function> defined =[C]:-1
 UNIT_THREAT_SITUATION_UPDATE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\threat.lua:29
 UNIT_THREAT_LIST_UPDATE = <function> defined @Interface\AddOns\SVUI_UnitFrames\libs\oUF\elements\threa

**Comment by drveoj** [comment]
Hi @kayleighraven - Can you download latest updates and see if that fixes your problem?

**Comment by kayleighraven** [comment]
Yup, have been playing for several hours now across all specs of my druid and no further errors :)

**Comment by drveoj** [comment]
Good news. Combopoints on druid still not 100% correct but that will come in the big unitframes revamp so happy to close this one. :)
