### ISSUE TITLE
Critical issue!

### ISSUE THREAD

**Issue by finalsliver** [joev/SVUI-Temp#87]
Joev has been working to hard and needs a break. 

Would advise afternoon off and away from Github. 
Additionally, light leveling and dungeoning may help to resolve any issues before the become noticable :p 

Well done so far Joev!
Much love for the updates and responses :)

**Comment by drveoj** [comment]
@finalsliver aww. I'm touched! :) 

Thanks but I've been very light the last week. just getting back into it today. Many bugs to fix! (and some major rework to do...)

**Comment by finalsliver** [comment]
Still don't burn out. 
Between WoW and Code you might find yourself with a bit much. 
Take one for the team and at least promise me you will have a cup of joe~

**Comment by drveoj** [comment]
Between Wow and code? In the last 3 weeks I've played about 2 hours of wow I think... I've had my client logged in for dozens... but only played very little... 

There is only code! :) 

joev

**Comment by finalsliver** [comment]
you need more WoW time stat!
once you hit 810 you can run heroics, and at 825 you qualify for LFR :)

**Comment by TiaMaster** [comment]
Already earned donations I would think after getting this working.  Don't know where to send.  
May wait til after Spec Switcher gets back in.  :)

**Comment by drveoj** [comment]
Refreshed and back on the horse. Clearing out a few long-standing issues then cracking on with Unitframes
